# Generated by Django 4.0.6 on 2022-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
